name: getx_multilanguage_helper
description: "Simplify multilanguage support in Flutter with GetX. Manage translations effortlessly, switch between languages, and enhance localization."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

